"repository":
  "name": "template"
  "description": "[WIP] Nix flake exposing the `template` PHP CLI application"
  "homepage": "https://github.com/nix-php/template"
  "topics": "ghostwriter, nix-php, template, template-repository"
  "private": false
  "has_issues": true
  "has_projects": false
  "has_wiki": false
  "has_downloads": true
  "default_branch": "0.1.x"
  "allow_squash_merge": true
  "allow_merge_commit": true
  "allow_rebase_merge": true
  "delete_branch_on_merge": true
  "enable_automated_security_fixes": true
  "enable_vulnerability_alerts": true
"milestones":
  - "title": "0.1.0"
    "description": "Minor release – targeting 0.1.x branch (semantic version: 0.1.0)"
    "state": "open"
  - "title": "1.0.0"
    "description": "Major release – targeting 1.0.x branch (semantic version: 1.0.0)"
    "state": "open"
